### ISSUE TITLE
Update dependencies to more current version of dustjs-linkedin

### ISSUE THREAD

**Issue by psyklopz** [lee-houghton/dusterjs#3]
The current dependencies in `package.json` restrict this to the 2.3.2 version of `dustjs-linkedin`.  I would like to see those dependencies softened.  By manually editing `package.json`, to the following:
  `"dependencies": {
    "watch": "*",
    "dustjs-linkedin": "*",
    "optimist": "*",
    "colors": "*",
    "diveSync": "*",
    "uglify-js": "*",
    "node-fs": "*"
  },`
I can get `npm` to update to the new version.  It still compiles my templates for me.
The update to the new version is crucial to my project, as I make heavy use of the new `@any` and `@none` selectors.

**Comment by lee-houghton** [comment]
I'll happily accept a pull request!  😃 

That said, you may wish to fork it and become the maintainer, as you will likely have much more time to commit to this than I do. The organisation  I work for has moved on to a new internal project which so I don't have much (if any) time to commit to this project.

**Comment by psyklopz** [comment]
Lee,
I would consider it an honor to become the maintainer of this project.  I use duster both at work and at home and really appreciate it as a piece of software.  I will fork it tonight and then put some more time testing my changes before publishing a new npm.

**Comment by lee-houghton** [comment]
I'd be more than happy to make you the owner of dusterjs on npm as well, if
you'd like. Just let me know your user name on npm and I'll add you.

**Comment by psyklopz** [comment]
Same username on npm, `psyklopz`
